"""
Seed data: 30+ realistic products across clothing, shoes, accessories, bags.
Indian brands, INR prices, realistic attributes.
"""
from app.database import SessionLocal
from app.models import Product


SEED_PRODUCTS = [
    # ─── CLOTHING (10 products) ──────────────────────────────────────────
    {
        "id": "prod_001",
        "name": "Classic Navy Blue Oxford Shirt",
        "description": "Premium cotton oxford shirt in navy blue. Perfect for office or smart-casual occasions. Breathable fabric with mother-of-pearl buttons.",
        "category": "clothing",
        "price": 1299.0,
        "currency": "INR",
        "stock": 45,
        "available": True,
        "attributes": {"color": "navy blue", "size": "M,L,XL", "brand": "FabIndia", "material": "cotton", "gender": "men"},
        "related_products": ["prod_002", "prod_003", "prod_010"],
    },
    {
        "id": "prod_002",
        "name": "Black Slim Fit Formal Shirt",
        "description": "Sleek black formal shirt in slim fit. Wrinkle-resistant fabric, ideal for meetings and events.",
        "category": "clothing",
        "price": 899.0,
        "currency": "INR",
        "stock": 60,
        "available": True,
        "attributes": {"color": "black", "size": "S,M,L,XL", "brand": "Peter England", "material": "poly-cotton", "gender": "men"},
        "related_products": ["prod_001", "prod_003", "prod_027"],
    },
    {
        "id": "prod_003",
        "name": "White Casual Linen Shirt",
        "description": "Lightweight white linen shirt for summer. Relaxed fit with a mandarin collar. Pairs well with chinos.",
        "category": "clothing",
        "price": 1499.0,
        "currency": "INR",
        "stock": 30,
        "available": True,
        "attributes": {"color": "white", "size": "M,L,XL,XXL", "brand": "FabIndia", "material": "linen", "gender": "men"},
        "related_products": ["prod_001", "prod_004", "prod_028"],
    },
    {
        "id": "prod_004",
        "name": "Printed Floral Kurti",
        "description": "Vibrant floral print kurti in soft rayon. Comfortable A-line cut, perfect for daily wear or festive occasions.",
        "category": "clothing",
        "price": 799.0,
        "currency": "INR",
        "stock": 55,
        "available": True,
        "attributes": {"color": "multicolor", "size": "S,M,L,XL", "brand": "W", "material": "rayon", "gender": "women"},
        "related_products": ["prod_005", "prod_006", "prod_023"],
    },
    {
        "id": "prod_005",
        "name": "Maroon Anarkali Kurta Set",
        "description": "Elegant maroon anarkali kurta with golden embroidery. Comes with matching dupatta and palazzo pants.",
        "category": "clothing",
        "price": 2499.0,
        "currency": "INR",
        "stock": 20,
        "available": True,
        "attributes": {"color": "maroon", "size": "S,M,L,XL", "brand": "Biba", "material": "silk-blend", "gender": "women"},
        "related_products": ["prod_004", "prod_006", "prod_024"],
    },
    {
        "id": "prod_006",
        "name": "Teal Cotton Palazzo Pants",
        "description": "Comfortable wide-leg palazzo pants in teal. Elasticated waist, perfect with kurtis or crop tops.",
        "category": "clothing",
        "price": 599.0,
        "currency": "INR",
        "stock": 70,
        "available": True,
        "attributes": {"color": "teal", "size": "S,M,L,XL,XXL", "brand": "W", "material": "cotton", "gender": "women"},
        "related_products": ["prod_004", "prod_005"],
    },
    {
        "id": "prod_007",
        "name": "Grey Melange Hoodie",
        "description": "Cozy grey melange hoodie with kangaroo pocket. Fleece-lined interior for winter comfort.",
        "category": "clothing",
        "price": 1199.0,
        "currency": "INR",
        "stock": 40,
        "available": True,
        "attributes": {"color": "grey", "size": "M,L,XL,XXL", "brand": "Roadster", "material": "cotton-fleece", "gender": "unisex"},
        "related_products": ["prod_008", "prod_013"],
    },
    {
        "id": "prod_008",
        "name": "Olive Green Cargo Joggers",
        "description": "Trendy olive cargo joggers with multiple pockets. Stretchable waist with drawstring. Street-style ready.",
        "category": "clothing",
        "price": 999.0,
        "currency": "INR",
        "stock": 35,
        "available": True,
        "attributes": {"color": "olive green", "size": "M,L,XL", "brand": "Roadster", "material": "cotton-twill", "gender": "men"},
        "related_products": ["prod_007", "prod_014"],
    },
    {
        "id": "prod_009",
        "name": "Red Checked Flannel Shirt",
        "description": "Classic red and black checked flannel shirt. Warm brushed cotton, great for autumn layering.",
        "category": "clothing",
        "price": 1099.0,
        "currency": "INR",
        "stock": 25,
        "available": True,
        "attributes": {"color": "red", "size": "S,M,L,XL", "brand": "Wrogn", "material": "flannel", "gender": "men"},
        "related_products": ["prod_001", "prod_007"],
    },
    {
        "id": "prod_010",
        "name": "Denim Blue Jacket",
        "description": "Classic indigo denim jacket with brass buttons. Timeless design that goes with everything.",
        "category": "clothing",
        "price": 1899.0,
        "currency": "INR",
        "stock": 18,
        "available": True,
        "attributes": {"color": "blue", "size": "M,L,XL", "brand": "Levi's", "material": "denim", "gender": "unisex"},
        "related_products": ["prod_001", "prod_009", "prod_013"],
    },

    # ─── SHOES (8 products) ──────────────────────────────────────────────
    {
        "id": "prod_011",
        "name": "Blue Mesh Running Sneakers",
        "description": "Lightweight blue mesh sneakers with cushioned sole. Ideal for running and daily workouts. Breathable and flexible.",
        "category": "shoes",
        "price": 1399.0,
        "currency": "INR",
        "stock": 50,
        "available": True,
        "attributes": {"color": "blue", "size": "7,8,9,10,11", "brand": "Campus", "type": "sneakers", "gender": "men"},
        "related_products": ["prod_012", "prod_013", "prod_008"],
    },
    {
        "id": "prod_012",
        "name": "White Classic Canvas Sneakers",
        "description": "Minimalist white canvas sneakers. Rubber sole with vulcanized construction. Goes with any outfit.",
        "category": "shoes",
        "price": 999.0,
        "currency": "INR",
        "stock": 65,
        "available": True,
        "attributes": {"color": "white", "size": "6,7,8,9,10,11", "brand": "Sparx", "type": "sneakers", "gender": "unisex"},
        "related_products": ["prod_011", "prod_014"],
    },
    {
        "id": "prod_013",
        "name": "Black Sports Training Shoes",
        "description": "All-black sports training shoes with memory foam insole. Anti-skid rubber outsole for gym and outdoor.",
        "category": "shoes",
        "price": 1799.0,
        "currency": "INR",
        "stock": 30,
        "available": True,
        "attributes": {"color": "black", "size": "7,8,9,10,11", "brand": "Nivia", "type": "training", "gender": "men"},
        "related_products": ["prod_011", "prod_007"],
    },
    {
        "id": "prod_014",
        "name": "Tan Leather Casual Loafers",
        "description": "Premium tan leather loafers with hand-stitched detailing. Cushioned footbed for all-day comfort.",
        "category": "shoes",
        "price": 2299.0,
        "currency": "INR",
        "stock": 22,
        "available": True,
        "attributes": {"color": "tan", "size": "7,8,9,10", "brand": "Hush Puppies", "type": "loafers", "gender": "men"},
        "related_products": ["prod_012", "prod_002"],
    },
    {
        "id": "prod_015",
        "name": "Pink Running Shoes for Women",
        "description": "Stylish pink running shoes with arch support and breathable mesh upper. Lightweight EVA sole.",
        "category": "shoes",
        "price": 1299.0,
        "currency": "INR",
        "stock": 40,
        "available": True,
        "attributes": {"color": "pink", "size": "4,5,6,7,8", "brand": "Campus", "type": "running", "gender": "women"},
        "related_products": ["prod_011", "prod_016"],
    },
    {
        "id": "prod_016",
        "name": "Beige Ethnic Juttis",
        "description": "Hand-embroidered beige juttis with mirror work. Traditional Rajasthani craftsmanship, comfortable flat sole.",
        "category": "shoes",
        "price": 699.0,
        "currency": "INR",
        "stock": 35,
        "available": True,
        "attributes": {"color": "beige", "size": "5,6,7,8", "brand": "Fizzy Goblet", "type": "ethnic", "gender": "women"},
        "related_products": ["prod_005", "prod_015", "prod_024"],
    },
    {
        "id": "prod_017",
        "name": "Grey Slip-On Walking Shoes",
        "description": "Ultra-comfortable grey slip-on walking shoes. Memory foam insole, knit upper, perfect for travel.",
        "category": "shoes",
        "price": 1099.0,
        "currency": "INR",
        "stock": 0,
        "available": False,
        "attributes": {"color": "grey", "size": "7,8,9,10", "brand": "Skechers", "type": "walking", "gender": "unisex"},
        "related_products": ["prod_012", "prod_014"],
    },
    {
        "id": "prod_018",
        "name": "Brown Ankle Boots",
        "description": "Rugged brown ankle boots with side zip. Genuine leather upper and anti-slip rubber sole.",
        "category": "shoes",
        "price": 2999.0,
        "currency": "INR",
        "stock": 15,
        "available": True,
        "attributes": {"color": "brown", "size": "7,8,9,10,11", "brand": "Woodland", "type": "boots", "gender": "men"},
        "related_products": ["prod_010", "prod_014"],
    },

    # ─── ACCESSORIES (7 products) ────────────────────────────────────────
    {
        "id": "prod_019",
        "name": "Silver Analog Watch",
        "description": "Elegant silver analog watch with stainless steel band. Water-resistant, mineral glass dial.",
        "category": "accessories",
        "price": 2499.0,
        "currency": "INR",
        "stock": 20,
        "available": True,
        "attributes": {"color": "silver", "brand": "Titan", "type": "watch", "gender": "men"},
        "related_products": ["prod_020", "prod_027"],
    },
    {
        "id": "prod_020",
        "name": "Rose Gold Women's Watch",
        "description": "Chic rose gold watch with mesh band. Slim profile, perfect for formal and casual wear.",
        "category": "accessories",
        "price": 1999.0,
        "currency": "INR",
        "stock": 25,
        "available": True,
        "attributes": {"color": "rose gold", "brand": "Fastrack", "type": "watch", "gender": "women"},
        "related_products": ["prod_019", "prod_024"],
    },
    {
        "id": "prod_021",
        "name": "Black Leather Belt",
        "description": "Genuine leather belt in black with brushed nickel buckle. 35mm width, auto-lock mechanism.",
        "category": "accessories",
        "price": 599.0,
        "currency": "INR",
        "stock": 80,
        "available": True,
        "attributes": {"color": "black", "brand": "Wildcraft", "type": "belt", "gender": "men"},
        "related_products": ["prod_002", "prod_027"],
    },
    {
        "id": "prod_022",
        "name": "Aviator Sunglasses - Gold Frame",
        "description": "Classic aviator sunglasses with gold metal frame and UV400 green tinted lenses.",
        "category": "accessories",
        "price": 1299.0,
        "currency": "INR",
        "stock": 30,
        "available": True,
        "attributes": {"color": "gold", "brand": "Vincent Chase", "type": "sunglasses", "gender": "unisex"},
        "related_products": ["prod_019", "prod_010"],
    },
    {
        "id": "prod_023",
        "name": "Embroidered Silk Dupatta",
        "description": "Handcrafted silk dupatta with zari embroidery. Rich jewel tones, perfect for festive occasions.",
        "category": "accessories",
        "price": 899.0,
        "currency": "INR",
        "stock": 40,
        "available": True,
        "attributes": {"color": "multicolor", "brand": "FabIndia", "type": "dupatta", "gender": "women"},
        "related_products": ["prod_004", "prod_005"],
    },
    {
        "id": "prod_024",
        "name": "Pearl Jhumka Earrings",
        "description": "Traditional pearl jhumka earrings with antique gold finish. Lightweight, suitable for daily wear.",
        "category": "accessories",
        "price": 499.0,
        "currency": "INR",
        "stock": 50,
        "available": True,
        "attributes": {"color": "gold", "brand": "Zaveri Pearls", "type": "earrings", "gender": "women"},
        "related_products": ["prod_020", "prod_005", "prod_016"],
    },
    {
        "id": "prod_025",
        "name": "Sports Digital Watch",
        "description": "Rugged digital sports watch with stopwatch, alarm, and backlight. Water-resistant to 50m.",
        "category": "accessories",
        "price": 799.0,
        "currency": "INR",
        "stock": 35,
        "available": True,
        "attributes": {"color": "black", "brand": "Casio", "type": "watch", "gender": "unisex"},
        "related_products": ["prod_019", "prod_013"],
    },

    # ─── BAGS (7 products) ───────────────────────────────────────────────
    {
        "id": "prod_026",
        "name": "Navy Blue Laptop Backpack",
        "description": "Spacious laptop backpack with padded 15.6-inch compartment. Water-resistant fabric with USB charging port.",
        "category": "bags",
        "price": 1499.0,
        "currency": "INR",
        "stock": 40,
        "available": True,
        "attributes": {"color": "navy blue", "brand": "American Tourister", "type": "backpack", "gender": "unisex"},
        "related_products": ["prod_027", "prod_022"],
    },
    {
        "id": "prod_027",
        "name": "Brown Leather Messenger Bag",
        "description": "Vintage-style brown leather messenger bag. Multiple compartments, adjustable strap, fits 13-inch laptop.",
        "category": "bags",
        "price": 2199.0,
        "currency": "INR",
        "stock": 18,
        "available": True,
        "attributes": {"color": "brown", "brand": "Hidesign", "type": "messenger", "gender": "men"},
        "related_products": ["prod_002", "prod_021", "prod_019"],
    },
    {
        "id": "prod_028",
        "name": "Cream Canvas Tote Bag",
        "description": "Minimalist cream canvas tote with leather handles. Spacious interior with zip pocket. Eco-friendly.",
        "category": "bags",
        "price": 699.0,
        "currency": "INR",
        "stock": 55,
        "available": True,
        "attributes": {"color": "cream", "brand": "Chumbak", "type": "tote", "gender": "women"},
        "related_products": ["prod_003", "prod_029"],
    },
    {
        "id": "prod_029",
        "name": "Black Structured Handbag",
        "description": "Elegant black structured handbag with gold-tone hardware. Faux leather, perfect for work and evenings.",
        "category": "bags",
        "price": 1799.0,
        "currency": "INR",
        "stock": 22,
        "available": True,
        "attributes": {"color": "black", "brand": "Lavie", "type": "handbag", "gender": "women"},
        "related_products": ["prod_028", "prod_020"],
    },
    {
        "id": "prod_030",
        "name": "Red Sling Crossbody Bag",
        "description": "Compact red sling bag with adjustable strap. Perfect for festivals, travel, and daily errands.",
        "category": "bags",
        "price": 599.0,
        "currency": "INR",
        "stock": 60,
        "available": True,
        "attributes": {"color": "red", "brand": "Lavie", "type": "sling", "gender": "women"},
        "related_products": ["prod_029", "prod_028"],
    },
    {
        "id": "prod_031",
        "name": "Military Green Duffel Bag",
        "description": "Large military green duffel bag for gym and travel. Heavy-duty nylon, shoe compartment, padded straps.",
        "category": "bags",
        "price": 1299.0,
        "currency": "INR",
        "stock": 28,
        "available": True,
        "attributes": {"color": "military green", "brand": "Wildcraft", "type": "duffel", "gender": "unisex"},
        "related_products": ["prod_026", "prod_013"],
    },
    {
        "id": "prod_032",
        "name": "Printed Jute Clutch",
        "description": "Artisan-printed jute clutch with magnetic closure. Handmade, eco-friendly, ideal for brunches and events.",
        "category": "bags",
        "price": 399.0,
        "currency": "INR",
        "stock": 45,
        "available": True,
        "attributes": {"color": "multicolor", "brand": "Chumbak", "type": "clutch", "gender": "women"},
        "related_products": ["prod_028", "prod_023"],
    },
]


def seed_database(db=None):
    """Seed the database with demo products. Idempotent — skips if products exist."""
    own_session = db is None
    if own_session:
        db = SessionLocal()
    try:
        existing = db.query(Product).count()
        if existing > 0:
            print(f"Database already has {existing} products. Skipping seed.")
            return existing

        for p in SEED_PRODUCTS:
            product = Product(
                id=p["id"],
                name=p["name"],
                description=p["description"],
                category=p["category"],
                price=p["price"],
                currency=p["currency"],
                stock=p["stock"],
                available=p["available"],
                attributes=p["attributes"],
                related_products=p["related_products"],
            )
            db.add(product)

        db.commit()
        count = db.query(Product).count()
        print(f"Seeded {count} products successfully.")
        return count
    except Exception as e:
        db.rollback()
        print(f"Seed error: {e}")
        raise
    finally:
        if own_session:
            db.close()


if __name__ == "__main__":
    from app.database import init_db
    init_db()
    seed_database()
